import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Providers from './providers'
import Nav from './ui/nav';
import Title from "./ui/title";
//import { useState, useContext, createContext } from "react";
import { Analytics } from "@vercel/analytics/react"
import { SpeedInsights } from "@vercel/speed-insights/next"

const inter = Inter({ subsets: ["latin"] });

/*export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};*/

//export const isSaradnikContext = createContext(false);

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  //const [isSaradnik, setSaradnik] = useState(false); 


  return (
    <html lang="en">
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" />
        <link href="https://fonts.googleapis.com/css2?family=Pacifico&display=swap" rel="stylesheet" />
        <meta name="google-site-verification" content="0gFnxdR_l8c4l3uVyQ5RBMNOy4HFeKvm-YU29A8G950" />
      </head>
      <body>
        <Providers>
          {/*<isSaradnikContext.Provider value={isSaradnik}>*/}
            <Title /> {/*setSaradnik={setSaradnik}*/}
            <Nav />
            {children}
            <Analytics />
            <SpeedInsights />
          {/*</isSaradnikContext.Provider>*/}
          </Providers>
      </body>
    </html>
  )
}